name: Test
on:
  workflow_dispatch:
permissions:
  actions: write
  contents: write
  issues: write
jobs:
  relabel-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: relabel
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const labelToFind = 'scheduled-next-release';
            const labelToAdd = 'fixed-pending-release';
            
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: labelToFind,
              per_page: 100
            });

            for (const issue of issues) {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                name: labelToFind
              });
              
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: [labelToAdd]
              });
            }
