name: Test
on:
  workflow_dispatch:
permissions:
  actions: write
  contents: write
  issues: write
jobs:
  relabel-issues:
    runs-on: ubuntu-latest
    steps:
      - name: search
        uses: actions/github-script@v7
        id: find_issues
        with:
          script: |
            const issues = await github.paginate(
              github.rest.issues.listForRepo,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                labels: 'scheduled-next-release',
                per_page: 100,
              }
            );
            return issues.map(issue => issue.number);

      - name: remove
        if: steps.find_issues.outputs.result != '[]'
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: scheduled-next-release
          number: ${{ fromJson(steps.find_issues.outputs.result)[0] }}

      - name: add
        if: steps.find_issues.outputs.result != '[]'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: fixed-pending-release
          number: ${{ fromJson(steps.find_issues.outputs.result)[0] }}
