name: Test
on:
  workflow_dispatch:
permissions:
  actions: write
  contents: write
  issues: write
jobs:
  relabel-issues:
    runs-on: ubuntu-latest
    steps:
      - name: find
        id: find_issues
        uses: peter-evans/find-issues@v3
        with:
          query: 'is:open label:scheduled-next-release'
          sort: created
          direction: asc

      - name: remove
        if: steps.find_issues.outputs.issues != ''
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.find_issues.outputs.issue-number }}
          labels: scheduled-next-release

      - name: add
        if: steps.find_issues.outputs.issues != ''
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ steps.find_issues.outputs.issue-number }}
          labels: fixed-pending-release
